package patches.projects

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.Project
import jetbrains.buildServer.configs.kotlin.projectFeatures.githubConnection
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the root project
accordingly, and delete the patch script.
*/
changeProject(DslContext.projectId) {
    params {
        add {
            param("sdf", "asdf")
        }
    }

    features {
        add {
            githubConnection {
                id = "PROJECT_EXT_331"
                displayName = "GitHub.com"
                clientId = "Ov23liXAC1ArwGwcpBz2"
                clientSecret = "credentialsJSON:7cfe4feb-3f6b-4708-abe9-b11743b16d49"
            }
        }
    }
}
