package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*
import jetbrains.buildServer.configs.kotlin.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a vcsRoot with id = 'HttpsGithubComHypnosphiGithubRefsHeadsMain'
in the root project, and delete the patch script.
*/
create(DslContext.projectId, GitVcsRoot({
    id("HttpsGithubComHypnosphiGithubRefsHeadsMain")
    name = "https://github.com/Hypnosphi/.github#refs/heads/main"
    url = "https://github.com/Hypnosphi/.github"
    branch = "refs/heads/main"
    branchSpec = "refs/heads/*"
    authMethod = password {
        userName = "Hypnosphi"
        password = "credentialsJSON:734be05b-23a9-49cb-9263-bbdafac9e224"
    }
    param("pipelines.connectionId", "PROJECT_EXT_331")
}))

